name: Bug Report
description: Do you have a bug report? We'd love to hear it!
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        We'll need some more information to fix it.
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Edge
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! We'll fix it as soon as possible.
